### ISSUE TITLE
如果每条弹幕长度不一样 会出现重叠问题

### ISSUE THREAD

**Issue by snmm23** [mCyp/Muti-Barrage#1]
如果每条弹幕长度不一样 会出现重叠问题

**Comment by mCyp** [comment]
应该是我的弹道选择算法出现了问题，会在下个版本更新

**Comment by mCyp** [comment]
重新测试了一下，是否是发射间隔设置太短了？碰撞检测并不是绝对的，它需要合理的发射间隔，如果短时间内发射的弹幕数量太多，前面的弹幕都还没有完全出来，肯定会出现重叠～这种情况还不知道如何处理，暂时的解决方法就是设置合理的发射间隔

**Comment by snmm23** [comment]
好的，明白了，谢谢
