### ISSUE TITLE
barrageView.destroy()执行之后，BarrageView中getSpeed方法中Log仍在打印

### ISSUE THREAD

**Issue by kevinmanager** [mCyp/Muti-Barrage#3]
BarrageView被销毁，该Log还在打印，说明某些资源还没有被关闭，我采用在BarrageAdapter的destroy方法中将mHandler置空，然后在mHandler发送消息和移除消息的都做了是否为空的判断解决了这个问题。还请原作者再检查一下代码，如有更好的解决方法，还麻烦原作者告知，以求共同进步，谢谢。

**Comment by mCyp** [comment]
我下班回去测试一下，感谢提问~

**Comment by mCyp** [comment]
我测试了一下，如果不置空会出现Bug，现代码已更正，还是谢谢老哥的指正~
